### ISSUE TITLE
Bug notes

### ISSUE THREAD

**Issue by sidaw** [sidaw/shrdlurn#53]
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at edu.stanford.nlp.sempre.BeamFloatingParserState.applyNonCatUnaryRules(BeamFloatingParser.java:303)
	at edu.stanford.nlp.sempre.BeamFloatingParserState.applyNonCatUnaryRules(BeamFloatingParser.java:324)
	at edu.stanford.nlp.sempre.BeamFloatingParserState.applyNonCatUnaryRules(BeamFloatingParser.java:324)
	at edu.stanford.nlp.sempre.BeamFloatingParserState.build(BeamFloatingParser.java:203)
	at edu.stanford.nlp.sempre.BeamFloatingParserState.infer(BeamFloatingParser.java:117)
	at edu.stanford.nlp.sempre.Parser.parse(Parser.java:172)
	at edu.stanford.nlp.sempre.Master.handleCommand(Master.java:478)
	at edu.stanford.nlp.sempre.Master.processQuery(Master.java:215)
	at edu.stanford.nlp.sempre.JsonServer$ExchangeState.processQuery(JsonServer.java:185)
	at edu.stanford.nlp.sempre.JsonServer$ExchangeState.handleQuery(JsonServer.java:229)
	at edu.stanford.nlp.sempre.JsonServer$ExchangeState.<init>(JsonServer.java:112)
	at edu.stanford.nlp.sempre.JsonServer$Handler.handle(JsonServer.java:57)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sidaw** [comment]
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:757)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:830)
	at edu.stanford.nlp.sempre.Json.readMapHard(Json.java:110)
	at edu.stanford.nlp.sempre.Json.readMapHard(Json.java:106)
	at edu.stanford.nlp.sempre.interactive.CitationTracker.writeSummary(CitationTracker.java:63)
	at edu.stanford.nlp.sempre.interactive.CitationTracker.citeRule(CitationTracker.java:48)
	at edu.stanford.nlp.sempre.interactive.CitationTracker.citeAll(CitationTracker.java:113)
	at edu.stanford.nlp.sempre.interactive.CitationTracker.citeAll(CitationTracker.java:118)
	at edu.stanford.nlp.sempre.interactive.CitationTracker.citeAll(CitationTracker.java:118)
	at edu.stanford.nlp.sempre.Master.handleCommand(Master.java:489)
	at edu.stanford.nlp.sempre.Master.processQuery(Master.java:215)
	at edu.stanford.nlp.sempre.JsonServer$ExchangeState.processQuery(JsonServer.java:185)
	at edu.stanford.nlp.sempre.JsonServer$ExchangeState.handleQuery(JsonServer.java:229)
	at edu.stanford.nlp.sempre.JsonServer$ExchangeState.<init>(JsonServer.java:112)
	at edu.stanford.nlp.sempre.JsonServer$Handler.handle(JsonServer.java:57)
